# Generated by Django 4.2.6 on 2023-11-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_question_content_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
